name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HealthManagerServer

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start SQL Server Container
      run: |
            docker run -d -p 1433:1433 --name sql_server_container -e ACCEPT_EULA=Y -e SA_PASSWORD=Zakuro19920120 mcr.microsoft.com/mssql/server:latest

    - name: Wait for SQL Server Initialization
      run: sleep 30

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      env:
        ConnectionStrings__TestDatabase: ${{ secrets.CONNECTION_STRINGS_TEST_DATABASE }}
        IssuerSigningKey: ${{ secrets.IssuerSigningKey }}
      run: dotnet test --no-build --verbosity normal

    - name: Stop and Remove SQL Server Container
      run: docker stop sql_server_container && docker rm sql_server_container
