name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./HealthManagerServer

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x # Use the appropriate version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      env:
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }} # Pass the connection string as an environment variable

    # You may want additional steps here for deployment, publishing artifacts, etc.
